before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - npm run build &
  - sleep 8
  - npm run server &
  - sleep 8
  - firefox http://localhost:5777/utest/ &
  - sleep 8


script:
  - "npm test"

language: node_js
node_js:
  - "6.10.0"
